Task 1:

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
mean = np.mean(a)
mean

3.0

In [5]:
st = np.std(a)
std

1.4142135623730951

Task 2

In [6]:
import numpy as np

m = np.random.rand(5, 5)
m

array([[0.19011798, 0.03939435, 0.40514571, 0.29503613, 0.74156184],
       [0.9836254 , 0.50689119, 0.35489761, 0.63320124, 0.5079877 ],
       [0.48522071, 0.54544902, 0.63871338, 0.34232319, 0.40002902],
       [0.94257593, 0.76629679, 0.48876757, 0.32954333, 0.77480745],
       [0.41076081, 0.30446322, 0.36897251, 0.26317792, 0.50666801]])

In [12]:

min_values_cols = np.min(m, axis=0)
max_values_cols = np.max(m, axis=0)

print("\nMinimum values along each column:")
print(min_values_cols)
print("\nMaximum values along each column:")
print(max_values_cols)



Minimum values along each column:
[0.19011798 0.03939435 0.35489761 0.26317792 0.40002902]

Maximum values along each column:
[0.9836254  0.76629679 0.63871338 0.63320124 0.77480745]


In [13]:
min_values_rows = np.min(m, axis=1)
max_values_rows = np.max(m, axis=1)

print("\nMinimum values along each row:")
print(min_values_rows)
print("\nMaximum values along each row:")
print(max_values_rows)


Minimum values along each row:
[0.03939435 0.35489761 0.34232319 0.32954333 0.26317792]

Maximum values along each row:
[0.74156184 0.9836254  0.63871338 0.94257593 0.50666801]


Task 3

In [14]:
import numpy as np

def cosine_similarity(v1, v2):
    dot_product = np.dot(v1, v2)
    magnitude_v1 = np.linalg.norm(v1)
    magnitude_v2 = np.linalg.norm(v2)
    cosine_similarity = dot_product / (magnitude_v1 * magnitude_v2)
    return cosine_similarity

In [15]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

cosine_similarity(v1, v2)

0.9746318461970762